/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_ls_ndk_MainActivity.h>
/* Header for class com_ls_ndk_MainActivity */

/*
 * Class:     com_ls_ndk_MainActivity
 * Method:    ndkGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ls_ndk_MainActivity_ndkGetString
  (JNIEnv * env, jobject obj){
  return (*env)->NewStringUTF(env,"First NDK");
  }
